name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [ gcc-10 ]
        include:
          - os: ubuntu-latest
            compiler: gcc-10
            target: Linux

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Make project
        run: make

      - name: Upload a Build Artifact
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PythOwOn.exe
          path: PythOwOn.exe

      - name: Upload a Build Artifact
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PythOwOn
          path: PythOwOn
